name: example
publish_to: none

environment:
  sdk: '>=2.19.0-0.dev <3.0.0'
  flutter: ">=3.7.0-0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_shader_kit:
    path: ../
  carousel_slider: ^5.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  # All shaders are from the package itself; no local shaders here

